--- 
title: "מבוא לתכנות ב R"
author: "אופיר בצר"
date: "2021-10-18"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
url: https://ophirbetser.github.io/intro_to_R_in_hebrew
link-citations: yes
github-repo: ophirbetser/intro_to_R_in_hebrew
---

# על הספר

הספר הזה נועד להיות מבוא בסיסי לתכנות בשפת
R
.
זהו אינו ספר העוסק בניתוח נתונים, ואין לקרוא אותו ככזה. בנוסף זהו אינו ספר אשר מומלץ ללמוד ממנו את אופן החשיבה הנרכש מקורסי מבוא למדעי המחשב. הספר מכוון לתת מבוא קצר, אך מעמיק מספיק לכלים תכנותים בסייסים, אשר בעזרתם ניתן ללמוד בהמשך נושאים תכנותיים מורכבים יותר. לדעתי יש יתרון בלהתחיל ללמוד קודם כל איך לכתוב קוד, אפילו לפני שלומדים כלים סטטיסטים הרלוונטים לניתוח הנתונים עצמו, כי יכולת התכנות הבסיסית עשויה להיות מאיימת ולא מזמינה, אך ברגע שמתחילים ״לשחק״ קצת עם הקוד, והנושא הופך לבהיר, מגלים כמה זה כיף, והתיאבון להמשך הלמידה גודל פלאים.

קריאה נעימה :)

## איך לקרוא את הספר וההדרכות 

את הספר אני ממליץ ללמוד פרק אחר פרק, ובמקביל לעבוד עם סקריפט 
R 
פתוח, ולנסות בעצמכם לממש ולייצר וריאציות של מה שמוצג. זוהי הדרך הטובה ביותר ללמוד, ולצבור ניסיון במגוון הדרכים השונות שאפשר לכתוב קוד.

בנוסף, עבור כל פרק בספר יצורף סרטון ווידאו שבו אעבור על החומר המוצג בספר. ניתן לצפות בסרטון במקביל לקריאה של הספר, עם זו דרך שבה אתם מעדיפים ללמוד.

## יצירת קשר

אם עולות שאלות, מצאתם שגיאת כתיב או חוסר דיוק, אשמח לשמוע.
אפשר ליצור איתי קשר דרך כתובת המייל
ophir.betser@gmail.com

---


עידכון אחרון:
`r lubridate::now()`

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```


